### ISSUE TITLE
Recipe Compile Error with ohai 4.0.0

### ISSUE THREAD

**Issue by mawatech** [zuazo/dovecot-cookbook#22]
See also the Changelog for version 4.0.0 https://supermarket.chef.io/cookbooks/ohai#changelog

Recipe: open-xchange-singlenode::dovecot
         * chef_gem[mail] action install
           - install version 2.6.4 of package mail
         
         ================================================================================
         Recipe Compile Error in /tmp/kitchen/cookbooks/qa-singlenode/recipes/default.rb
         ================================================================================
         
         NoMethodError
         -------------
         undefined method `[]' for nil:NilClass
         
         Cookbook Trace:
         ---------------
           /tmp/kitchen/cookbooks/dovecot/recipes/ohai_plugin.rb:33:in `from_file'
           /tmp/kitchen/cookbooks/dovecot/recipes/default.rb:22:in `from_file'
           /tmp/kitchen/cookbooks/open-xchange-singlenode/recipes/dovecot.rb:35:in `from_file'
           /tmp/kitchen/cookbooks/open-xchange-singlenode/recipes/mailstore.rb:9:in `from_file'
           /tmp/kitchen/cookbooks/qa-singlenode/recipes/default.rb:116:in `from_file'
         
         Relevant File Content:
         ----------------------
         /tmp/kitchen/cookbooks/dovecot/recipes/ohai_plugin.rb:
         
          26:  source_dir = ohai7? ? 'ohai7_plugins' : 'ohai_plugins'
          27:  
          28:  ohai 'reload_dovecot' do
          29:    plugin 'dovecot'
          30:    action :nothing
          31:  end
          32:  
          33>> template "#{node['ohai']['plugin_path']}/dovecot.rb" do
          34:    source "#{source_dir}/dovecot.rb.erb"
          35:    owner 'root'
          36:    group 'root'
          37:    mode '0755'
          38:    variables(
          39:      enable_build_options: node['dovecot']['ohai_plugin']['build-options']
          40:    )
          41:    notifies :reload, 'ohai[reload_dovecot]', :immediately
          42:  end
         
         Platform:
         ---------
         x86_64-linux
         
         
         Running handlers:
       [2016-05-19T06:53:55+00:00] ERROR: Running exception handlers
         Running handlers complete

**Comment by zuazo** [comment]
Thank you for reporting the issue, @mawatech.

Until the fix is ready, you will need to set `ohai` cookbook version to `3` using your wrapper cookbook:

```ruby
# metadata.rb
depends 'ohai', '~> 3.0'
```

**Comment by mawatech** [comment]
Thx for your reply, i already did this and i can confirm that this "workaround" works :-)

**Comment by ericgoedtel** [comment]
I actually had to set this in the Berksfile and not the metadata.rb file. Is that expected?

**Comment by zuazo** [comment]
You can use the *Berksfile* if you prefer. But in the metadata it should also work.

**Comment by zuazo** [comment]
We have udpated the code to work with ohai cookbook version 4 in #23 and fixed this in f5ccd8266c4c64ec282f88f823d8fbbdfab91a4c.

**Comment by zuazo** [comment]
I have released version [`2.5.0`](https://github.com/zuazo/dovecot-cookbook/releases/tag/2.5.0) with the fix, but using `ohai` cookbook version `3`.

The update to version `4` will be released in version `3.0.0` because it breaks Chef 11 compatibility.

**Comment by lamont-granquist** [comment]
@zuazo this version 2.5.0 of this cookbook will not depsolve with e.g. the chef_nginx cookbook which pins ohai to ~> 4.0, needs a 3.0 release that drops 11.x support

**Comment by zuazo** [comment]
OK, thanks @lamont-granquist. I'm going to try to make a release tomorrow.

**Comment by lamont-granquist** [comment]
my home mailserver thanks you =)

**Comment by zuazo** [comment]
Your are welcome ;-)

Ohai cookbook `4` support released in [`3.0.0`](https://github.com/zuazo/dovecot-cookbook/releases/tag/3.0.0).

**Comment by lamont-granquist** [comment]
👍
